<template>
    <Card
        ref="root"
        :class="[
            'nova-card-html',
            `nova-card-html-theme-${card.theme || 'default'}`,
            alignClass,
            paddingClass,
        ]"
        :style="cardStyles"
    >
        <!-- Card-scoped CSS, so cards no longer have to emit <style> from PHP. -->
        <component :is="'style'" v-if="card.styles">{{
            card.styles
        }}</component>

        <div v-if="hasHeading" class="nova-card-html-heading">
            <component
                :is="collapsible ? 'button' : 'div'"
                :type="collapsible ? 'button' : null"
                class="nova-card-html-heading-inner"
                :aria-expanded="collapsible ? String(!collapsed) : null"
                @click="collapsible ? (collapsed = !collapsed) : null"
            >
                <Icon
                    v-if="card.icon"
                    :name="card.icon"
                    type="micro"
                    class="nova-card-html-icon"
                />

                <h2 v-if="card.title" class="nova-card-html-title">
                    {{ card.title }}
                </h2>

                <Icon
                    v-if="collapsible"
                    :name="collapsed ? 'chevron-down' : 'chevron-up'"
                    type="micro"
                    class="nova-card-html-chevron"
                />
            </component>
        </div>

        <template v-if="!collapsed">
            <div v-if="card.header" v-html="card.header" />

            <div
                v-if="showSkeleton"
                class="nova-card-html-body"
                :style="bodyStyles"
            >
                <CardSkeleton v-if="!card.placeholder" />
                <div v-else v-html="card.placeholder" />
            </div>

            <div
                v-else-if="failed"
                class="nova-card-html-body nova-card-html-error"
            >
                <p>{{ __("Could not load this card.") }}</p>
                <button type="button" class="link-default" @click="reload">
                    {{ __("Retry") }}
                </button>
            </div>

            <div
                v-else
                class="nova-card-html-body"
                :class="{ 'nova-card-html-scroll': isScrollable }"
                :style="bodyStyles"
            >
                <div v-html="content" />
            </div>

            <div v-if="card.footer" v-html="card.footer" />
        </template>
    </Card>
</template>

<script setup>
import { computed, ref } from "vue";
import CardSkeleton from "./CardSkeleton.vue";
import { useLazyContent } from "../composables/useLazyContent";

const props = defineProps({
    card: {
        type: Object,
        required: true,
    },
});

const root = ref(null);

const { content, loading, failed, reload } = useLazyContent(props.card, root);

const collapsible = computed(() => Boolean(props.card.collapsible));
const collapsed = ref(Boolean(props.card.collapsedByDefault));

const hasHeading = computed(
    () =>
        Boolean(props.card.title) ||
        Boolean(props.card.icon) ||
        collapsible.value,
);

const isScrollable = computed(() => props.card.height === "fixed");

// A lazy card has no content between mount and the first response landing --
// including before the request starts, and while deferUntilVisible waits for
// the card to scroll into view. Show the placeholder for that whole window
// rather than only while a request is in flight, or the card renders blank.
const showSkeleton = computed(
    () => props.card.lazy && !content.value && !failed.value,
);

const alignClass = computed(() => {
    const align = props.card.align ?? (props.card.center ? "center" : "left");

    return `nova-card-html-align-${align}`;
});

const paddingClass = computed(() =>
    props.card.cardStyles === false ? "nova-card-html-bare" : "px-6 py-4",
);

const cardStyles = computed(() =>
    props.card.cardStyles === false
        ? { background: "none", border: "none", boxShadow: "none" }
        : {},
);

/**
 * Heights are inline rather than Tailwind arbitrary values: those classes are
 * only generated by the host application's own Tailwind build, so they silently
 * did nothing in a packaged card.
 */
const bodyStyles = computed(() => {
    if (props.card.height !== "fixed") {
        return {};
    }

    const max = props.card.maxHeight ?? (props.card.title ? 90 : 128);

    return { maxHeight: `${max}px`, minHeight: `${max}px` };
});
</script>
